import type { CompletionSound } from "@t3tools/contracts";
import { toastManager } from "../components/ui/toast";

const AVANTI_SAMPLE_URL = "/avanti.mp3";
const AVANTI_SAMPLE_VOLUME = 0.28;
// Generated by scripts/generate-resolve-sound.ts with the playback volume baked in.
const RESOLVE_SAMPLE_URL = "/resolve.wav";
const WINDOWS_TADA_SAMPLE_URL = "/_desktop/windows-tada.wav";
const WINDOWS_TADA_SAMPLE_VOLUME = 1;
const WINDOWS_TADA_SAMPLE_GAIN = 3;

let completionAudioContext: AudioContext | null = null;
const sampleAudioByUrl = new Map<string, HTMLAudioElement>();
const amplifiedSampleGraphByUrl = new Map<
  string,
  { source: MediaElementAudioSourceNode; gain: GainNode }
>();
let reportedWindowsTadaUnavailable = false;

function getCompletionAudioContext(): AudioContext | null {
  if (typeof AudioContext === "undefined") {
    return null;
  }

  if (completionAudioContext?.state === "closed") {
    completionAudioContext = null;
  }
  completionAudioContext ??= new AudioContext();
  return completionAudioContext;
}

export function playSoundSample(
  url: string,
  volume: number,
  onMediaError?: () => void,
  gainMultiplier = 1,
): void {
  if (typeof Audio === "undefined") {
    return;
  }

  let audio = sampleAudioByUrl.get(url);
  if (audio === undefined) {
    audio = new Audio(url);
    audio.preload = "auto";
    const sample = audio;
    sample.addEventListener("error", () => {
      // MEDIA_ERR_ABORTED is an interruption, not an unavailable file.
      if (sample.error && sample.error.code !== 1) {
        sampleAudioByUrl.delete(url);
        const graph = amplifiedSampleGraphByUrl.get(url);
        graph?.source.disconnect();
        graph?.gain.disconnect();
        amplifiedSampleGraphByUrl.delete(url);
        onMediaError?.();
      }
    });
    sampleAudioByUrl.set(url, audio);
  }

  if (gainMultiplier > 1 && !amplifiedSampleGraphByUrl.has(url)) {
    try {
      const audioContext = getCompletionAudioContext();
      if (audioContext !== null) {
        const source = audioContext.createMediaElementSource(audio);
        const gain = audioContext.createGain();
        gain.gain.value = gainMultiplier;
        source.connect(gain).connect(audioContext.destination);
        amplifiedSampleGraphByUrl.set(url, { source, gain });
        if (audioContext.state === "suspended") {
          void audioContext.resume();
        }
      }
    } catch {
      // Fall back to the media element's unamplified output.
    }
  }

  audio.volume = Math.max(0, Math.min(1, volume));
  audio.pause();
  audio.currentTime = 0;
  void audio.play().catch(() => {
    // Browser autoplay policy can block this until the user interacts with the page.
  });
}

export function playCompletionSound(sound: CompletionSound): void {
  if (sound === "none") {
    return;
  }
  if (sound === "avanti") {
    playSoundSample(AVANTI_SAMPLE_URL, AVANTI_SAMPLE_VOLUME);
    return;
  }
  if (sound === "windows-tada") {
    playSoundSample(
      WINDOWS_TADA_SAMPLE_URL,
      WINDOWS_TADA_SAMPLE_VOLUME,
      () => {
        if (reportedWindowsTadaUnavailable) return;
        reportedWindowsTadaUnavailable = true;
        toastManager.add({
          type: "error",
          title: "Windows Ta-da is unavailable",
          description:
            "The Windows sound file could not be loaded. Choose another completion sound in Settings → General.",
        });
      },
      WINDOWS_TADA_SAMPLE_GAIN,
    );
    return;
  }
  playSoundSample(RESOLVE_SAMPLE_URL, 1);
}
