import type { CompletionSound } from "@t3tools/contracts";

const AVANTI_SAMPLE_URL = "/avanti.mp3";
const AVANTI_SAMPLE_VOLUME = 0.28;
// Generated by scripts/generate-resolve-sound.ts with the playback volume baked in.
const RESOLVE_SAMPLE_URL = "/resolve.wav";

const sampleAudioByUrl = new Map<string, HTMLAudioElement>();

export function playSoundSample(url: string, volume: number): void {
  if (typeof Audio === "undefined") {
    return;
  }

  let audio = sampleAudioByUrl.get(url);
  if (audio === undefined) {
    audio = new Audio(url);
    audio.preload = "auto";
    sampleAudioByUrl.set(url, audio);
  }

  audio.volume = Math.max(0, Math.min(1, volume));
  audio.pause();
  audio.currentTime = 0;
  void audio.play().catch(() => {
    // Browser autoplay policy can block this until the user interacts with the page.
  });
}

export function completionSoundSample(sound: CompletionSound) {
  if (sound === "none") return null;
  return sound === "avanti"
    ? { url: AVANTI_SAMPLE_URL, volume: AVANTI_SAMPLE_VOLUME }
    : { url: RESOLVE_SAMPLE_URL, volume: 1 };
}

export function playCompletionSound(sound: CompletionSound): void {
  const sample = completionSoundSample(sound);
  if (sample) playSoundSample(sample.url, sample.volume);
}
